name: Deploy Sanity Studio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: studio

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Studio
        run: npm run build
        env:
          SANITY_STUDIO_GOOGLE_MAPS_API_KEY: ${{secrets.SANITY_STUDIO_GOOGLE_MAPS_API_KEY}}

      - name: Deploy Sanity Studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
          SANITY_STUDIO_GOOGLE_MAPS_API_KEY: ${{secrets.SANITY_STUDIO_GOOGLE_MAPS_API_KEY}}
        run: npx sanity deploy --yes
