name: Deploy Sanity Studio

on:
  push:
    branches:
      - main
    paths:
      - "studio/**"
      - "package-lock.json"
      - ".nvmrc"
      - ".github/workflows/deploy-sanity.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: studio

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build Studio
        env:
          SANITY_STUDIO_GOOGLE_MAPS_API_KEY: ${{secrets.SANITY_STUDIO_GOOGLE_MAPS_API_KEY}}
        run: npm run build

      - name: Deploy Sanity Studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }}
          SANITY_STUDIO_GOOGLE_MAPS_API_KEY: ${{secrets.SANITY_STUDIO_GOOGLE_MAPS_API_KEY}}
        run: npx sanity deploy --yes
